// src/app/models/job-offer.model.ts

export interface JobOffer {
  id?: number;             // optional if generated by backend
  title: string;
  description: string;
  company: string;
  location: string;
  postedDate: Date | string;
  // Add other attributes based on your backend entity
}
