apiVersion: v1
kind: Service
metadata:
  name: nomprenomlasseexamen-backend
spec:
  selector:
    app: nomprenomlasseexamen-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8089
  type: LoadBalancer
