apiVersion: v1
kind: Service
metadata:
  name: nomprenomlasseexamen-backend
spec:
  selector:
    app: nomprenomlasseexamen-backend
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
      nodePort: 30089
  type: NodePort
