apiVersion: apps/v1
kind: Deployment
metadata:
  name: nomprenomlasseexamen-backend
  labels:
    app: nomprenomlasseexamen-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nomprenomlasseexamen-backend
  template:
    metadata:
      labels:
        app: nomprenomlasseexamen-backend
    spec:
      imagePullSecrets:
        - name: nexus-creds
      containers:
      - name: backend
        image: 192.168.220.151:5000/nomprenomlasseexamen-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8089
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://mysql:3306/PGH_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
          - name: SPRING_DATASOURCE_USERNAME
            value: root
          - name: SPRING_DATASOURCE_PASSWORD
            value: rootpassword
          - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
            value: com.mysql.cj.jdbc.Driver
        readinessProbe:
          httpGet:
            path: /PGH/actuator/health/readiness
            port: 8089
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /PGH/actuator/health/liveness
            port: 8089
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        # Add init container to wait for MySQL
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.35
        command: ['sh', '-c']
        args:
          - |
            echo "Waiting for MySQL to be ready..."
            until nc -z mysql 3306; do
              echo "MySQL not ready, waiting..."
              sleep 5
            done
            echo "MySQL is ready!"
