apiVersion: apps/v1
kind: Deployment
metadata:
  name: nomprenomlasseexamen-frontend
  labels:
    app: nomprenomlasseexamen-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nomprenomlasseexamen-frontend
  template:
    metadata:
      labels:
        app: nomprenomlasseexamen-frontend
    spec:
      imagePullSecrets:
      - name: dockerhub-secret 
      containers:
      - name: frontend
        image: ranya631/nomprenomlasseexamen-frontend:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 80
